#!/usr/bin/env bash
# Debugging made short
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
echo "\ndaemon off;" >> /etc/nginx/nginx.conf
chown -R www-data:www-data /var/lib/nginx
